#!/bin/bash 
#
# Checks which hosts in your /etc/hosts file are up or down
# Author: Tom Dignan <tom.dignan@gmail.com>

ENABLE_IPV6=false
GREEN="\033[0;32m"
RED="\033[0;31m"
RESET="\033[0m"

#ipv4
cat /etc/hosts | grep -v '^#' | grep -v "^$" | grep -v "::" | tr '\t' ' ' | \
cut -d ' ' -f1  | xargs -I@ echo ping -W2 -c1 @ '&>/dev/null' '&&' echo -e @ \
'"\\t\\t"' "\"[${GREEN}OK${RESET}]\"" '||' echo -e @ '"\\t\\t"' "\"[${RED}DOWN${RESET}]\"" | bash

if [ $ENABLE_IPV6 == true ]
then
    #ipv6 
    cat /etc/hosts | grep -v '^#' | grep -v "^$" | grep "::"| tr '\t' ' ' | \
    cut -d ' ' -f1 | xargs -I@ echo ping6 -W2 -c1 @ '&>/dev/null' '&&' echo -e @ \
    '"\\t\\t"' "\"[${GREEN}OK${RESET}]\"" '||' echo -e @ '"\\t\\t"' "\"[${RED}DOWN${RESET}]\"" \
    | bash
fi



